### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by NeikiDev** [ttc-cert/TTC-CERT_blocklist_recommended#2]
Hey,

I am the owner of the Domain "neiki.dev".

Recently i found out that my domain "analyze.neiki.dev" is blocked in this list

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt

Please remove this domain from the blocklist.

As you can see i use this domain for virustotal analysis and more, its a domain that stores information about files (Malware reports and more) to keep the community safe.

You can see here on virustotal https://www.virustotal.com/gui/user/NeikiAnalytics that i have a good record and reputation and my domain is in no way malicious or related to ads.

Please let me also know why it got blocked in the first place.

https://github.com/hagezi/dns-blocklists/issues/2519

Thanks, Neiki

**Comment by ttc-cert** [comment]
Dear Neiki,

Thank you for reaching out regarding the blockage of "analyze.neiki.dev" in the DNS blocklist. I sincerely apologize for any inconvenience this may have caused you.

Upon investigating the issue, I discovered that there was a flaw in my script, which inadvertently flagged your domain due to data retrieved from a specific source. Specifically, the data from https://research.checkpoint.com/2024/maldocs-of-word-and-excel-vigor-of-the-ages/ in the "Spreading Agent Tesla in 2023" section was mistakenly considered an indicator of compromise.

I take full responsibility for this oversight and I deeply regret any disruption this has caused to your services. Please rest assured that your domain "analyze.neiki.dev" is not malicious or related to ads in any way. I will promptly rectify this issue by removing "analyze.neiki.dev" from the blocklist. You can expect the domain to be unblocked by April 18, 2024, at 03:00 GMT+7.

Again, I apologize for any inconvenience caused, and I appreciate your understanding and patience in this matter. If you have any further questions or concerns, please don't hesitate to reach out.

Best regards,

TTC-CERT

**Comment by NeikiDev** [comment]
Thank you for fixing the issue and resolving the problem.

I appreciate the fast response and i can understand what happend dont worry.
